name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format --check

      - name: Run build
        run: pnpm build

      - name: Run tests
        run: pnpm test:ci
